- name: Deploy Docker App to EC2 Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install required packages for Docker
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
        filename: docker

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: true

    - name: Create app directory
      file:
        path: /home/ubuntu/webapp
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy application files
      copy:
        src: ../webapp/
        dest: /home/ubuntu/webapp/
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Build Docker image
      command: sudo docker build -t webapp /home/ubuntu/webapp
      args:
        chdir: /home/ubuntu/webapp

    - name: Run Docker container
      command: sudo docker run -d --restart unless-stopped --name webapp -p 80:80 webapp
